"use strict";
const SITE_KEYS=["chatgpt","grok","claude","discord","slack"];let lastStatus=null;
function $(id){const el=document.getElementById(id);if(!el)throw new Error("missing #"+id);return el}
async function getJSON(path){const r=await fetch(path,{cache:"no-store"});if(!r.ok)throw new Error(path+" "+r.status);return r.json()}
async function postJSON(path,body){const r=await fetch(path,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body??{})});if(!r.ok){let extra="";try{const j=await r.json();extra=j.error?": "+j.error:""}catch{}throw new Error(path+" "+r.status+extra)}return r.json()}
function renderStatus(s,d){lastStatus=s;$("st-state").textContent=s.state;$("st-theme").textContent=s.theme;const gs=d.ghostty.installed?(d.ghostty.default?"default":"installed / not default"):"missing";$("st-ghostty").textContent=[gs,d.ghostty.version].filter(Boolean).join(" · ");$("st-launcher").textContent=d.launcher.name+" · "+d.launcher.keybind;$("st-gost").textContent=(s.gost.enabled?"enabled":"off")+" / "+(s.gost.running?"running":"stopped");$("st-clis").textContent=[s.clis.installed,s.clis.preexisting].filter(Boolean).join(" ")||"—";$("st-api").textContent=s.api.listen;renderListen(s.api)}
function renderListen(api){$("listen-api").textContent="API "+(api.api_public?"public":"loopback");$("listen-api").className="state-chip"+(api.api_public?" public":"");$("listen-ui").textContent="Settings "+(api.ui_public?"public":"loopback");$("listen-ui").className="state-chip"+(api.ui_public?" public":"");$("listen-effective").textContent="listen "+api.listen}
function renderDefaults(d){$("default-ai").value=d.default_ai_chat;SITE_KEYS.forEach(k=>$("site-"+k).value=d.sites[k]||"");const list=$("shortcuts");list.textContent="";const entries=[["Super+Space","launcher"],["MaxQ AI Chat",d.sites[d.default_ai_chat]||d.default_ai_chat],["ChatGPT",d.sites.chatgpt],["Grok",d.sites.grok],["Claude",d.sites.claude],["Discord",d.sites.discord],["Slack",d.sites.slack],["Ghostty","$HOME/bin/ghostty"],["MaxQ Settings",window.location.origin]];for(const [name,target] of entries){const li=document.createElement("li"),r=document.createElement("span");r.textContent=target||"—";li.append(document.createTextNode(name),r);list.appendChild(li)}}
function renderPackages(items){const list=$("packages");list.textContent="";for(const p of items){const li=document.createElement("li"),r=document.createElement("span");r.textContent=[p.version,p.source,p.path].filter(Boolean).join(" · ");li.append(document.createTextNode(p.name),r);list.appendChild(li)}if(!items.length){const li=document.createElement("li");li.textContent="No SBOM entries yet";list.appendChild(li)}}
function readDefaults(){const sites={};SITE_KEYS.forEach(k=>sites[k]=$("site-"+k).value.trim());return{default_ai_chat:$("default-ai").value,sites}}
function msg(text,ok=false){const e=$("msg");e.hidden=!text;e.textContent=text;e.style.color=ok?"var(--green)":"var(--red)"}
async function refresh(){const [s,d,defs,sbom]=await Promise.all([getJSON("/status"),getJSON("/desktop"),getJSON("/defaults"),getJSON("/sbom")]);renderStatus(s,d);renderDefaults(defs);renderPackages(sbom)}
function busy(on){["btn-apply","btn-revert","btn-proxy-on","btn-proxy-off","btn-save-defaults","btn-api-public","btn-api-loopback","btn-ui-public","btn-ui-loopback"].forEach(id=>$(id).disabled=on)}
async function act(fn,success=""){msg("");busy(true);try{await fn();await refresh();if(success)msg(success,true)}catch(e){msg(e instanceof Error?e.message:String(e))}finally{busy(false)}}
async function listenAct(body){msg("");busy(true);try{const r=await postJSON("/listen",body);renderListen({api_public:r.api_public,ui_public:r.ui_public,listen:r.effective_listen});if(r.restart_required)msg("listen policy saved · restart required for bind change",true);else msg("listen policy saved",true);try{await refresh()}catch{}}catch(e){msg(e instanceof Error?e.message:String(e))}finally{busy(false)}}
window.addEventListener("DOMContentLoaded",()=>{$("btn-apply").addEventListener("click",()=>act(()=>postJSON("/apply",{})));$("btn-revert").addEventListener("click",()=>act(()=>postJSON("/revert",{})));$("btn-proxy-on").addEventListener("click",()=>act(()=>postJSON("/proxy",{enabled:true})));$("btn-proxy-off").addEventListener("click",()=>act(()=>postJSON("/proxy",{enabled:false})));$("defaults-form").addEventListener("submit",e=>{e.preventDefault();act(()=>postJSON("/defaults",readDefaults()),"defaults saved")});$("btn-api-public").addEventListener("click",()=>listenAct({api_public:true}));$("btn-api-loopback").addEventListener("click",()=>listenAct({api_public:false}));$("btn-ui-public").addEventListener("click",()=>listenAct({ui_public:true}));$("btn-ui-loopback").addEventListener("click",()=>listenAct({ui_public:false}));refresh().catch(e=>msg(e instanceof Error?e.message:String(e)))})
