// MaxQ settings sheet (compiled from sheet.ts; no framework).
"use strict";
function $(id) { const el = document.getElementById(id); if (!el) throw new Error("missing #" + id); return el; }
async function requestJSON(path, init) { const r = await fetch(path, init); if (!r.ok) { let extra = ""; try { const j = await r.json(); extra = j.error ? ": " + j.error : ""; } catch {} throw new Error(path + " " + r.status + extra); } if (r.status === 204) return undefined; return r.json(); }
async function getStatus() { return requestJSON("/status"); }
async function getPolicy() { return requestJSON("/policy"); }
async function getHAAllowlist() { return requestJSON("/ha/allowlist"); }
async function getConnections() { return requestJSON("/connections"); }
async function getDesktops() { return requestJSON("/desktops"); }
async function postJSON(path, body) { return requestJSON(path, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(body ?? {}) }); }
async function putJSON(path, body) { return requestJSON(path, { method: "PUT", headers: { "content-type": "application/json" }, body: JSON.stringify(body ?? {}) }); }
function renderStatus(s) { $("st-state").textContent = s.state; $("st-theme").textContent = s.theme; $("st-gost").textContent = (s.gost.enabled ? "enabled" : "off") + " / " + (s.gost.running ? "running" : "stopped"); $("st-clis").textContent = [s.clis.installed, s.clis.skipped].filter((x) => x && x.length).join(" ") || "—"; $("st-api").textContent = s.api.listen; const pill = $("pill"); pill.textContent = s.state; pill.className = "pill " + (s.state === "applied" ? "on" : "off"); }
function renderStatusUnavailable(message) { ["st-state", "st-theme", "st-gost", "st-clis"].forEach((id) => { $(id).textContent = "Unavailable"; }); const pill = $("pill"); pill.textContent = "status error"; pill.className = "pill off"; $("st-api").textContent = message; }
let policyAvailable = false;
let networkAvailable = false;
let haAvailable = false;
let busyState = false;
let haEntities = [];
function renderPolicy(policy) { policyAvailable = true; const enabled = $("approvals-enabled"); enabled.checked = policy.approvals.mode === "on"; enabled.disabled = busyState; $("st-approvals").textContent = policy.approvals.mode === "off" ? "Off · always allow · host Auto-review bypassed" : "On · approval prompts allowed"; }
function renderPolicyUnavailable(message) { policyAvailable = false; const enabled = $("approvals-enabled"); enabled.checked = false; enabled.disabled = true; $("st-approvals").textContent = "Unavailable · " + message; }
function syncNetworkFields() { const mode = $("network-mode"); const loginServer = $("network-login-server"); const headscale = mode.value === "headscale"; $("headscale-fields").hidden = !headscale; loginServer.required = headscale; }
function renderNetwork(network) { networkAvailable = true; const mode = $("network-mode"); const loginServer = $("network-login-server"); mode.value = network.mode; loginServer.value = network.login_server || ""; syncNetworkFields(); const parts = [network.mode === "headscale" ? "Headscale" : "Tailscale"]; if (network.status) parts.push(network.status === "down" ? "Disconnected" : "Up"); if (network.mode === "headscale" && network.login_server) parts.push(network.login_server); if (network.auth_key_configured) parts.push("auth key stored"); $("st-network").textContent = parts.join(" · "); mode.disabled = busyState; loginServer.disabled = busyState; $("network-auth-key").disabled = busyState; $("btn-network-save").disabled = busyState; $("btn-network-leave").disabled = busyState; }
function renderNetworkUnavailable(message) { networkAvailable = false; ["network-mode", "network-login-server", "network-auth-key", "btn-network-save", "btn-network-leave"].forEach((id) => { $(id).disabled = true; }); $("st-network").textContent = "Unavailable · " + message; }
function renderHA() { const list = $("ha-entities"); list.replaceChildren(); if (!haEntities.length) { const empty = document.createElement("li"); empty.className = "muted"; empty.textContent = "Allowlist is empty. No HA entities are bot-visible."; list.append(empty); } else { haEntities.forEach((entity, index) => { const item = document.createElement("li"); item.className = "connection"; const text = document.createElement("div"); const id = document.createElement("strong"); id.textContent = entity.id; text.append(id); if (entity.label) { const detail = document.createElement("small"); detail.textContent = entity.label; text.append(detail); } const remove = document.createElement("button"); remove.type = "button"; remove.className = "remove"; remove.textContent = "Remove"; remove.addEventListener("click", () => { haEntities.splice(index, 1); renderHA(); }); item.append(text, remove); list.append(item); }); } $("st-ha").textContent = haEntities.length + " curated entit" + (haEntities.length === 1 ? "y" : "ies") + " · not a full HA inventory"; $("ha-entity-id").disabled = busyState || !haAvailable; $("ha-entity-label").disabled = busyState || !haAvailable; $("btn-ha-add").disabled = busyState || !haAvailable; $("btn-ha-save").disabled = busyState || !haAvailable; }
function renderHAAllowlist(allowlist) { haAvailable = true; haEntities = Array.isArray(allowlist.entities) ? allowlist.entities.map((entity) => ({ id: entity.id, label: entity.label || "" })) : []; renderHA(); }
function renderHAUnavailable(message) { haAvailable = false; haEntities = []; const list = $("ha-entities"); list.replaceChildren(); const item = document.createElement("li"); item.className = "msg"; item.textContent = "Unavailable · " + message; list.append(item); $("st-ha").textContent = "Unavailable · " + message; ["ha-entity-id", "ha-entity-label", "btn-ha-add", "btn-ha-save"].forEach((id) => { $(id).disabled = true; }); }
function addHAEntityFromInputs() { const idInput = $("ha-entity-id"); const labelInput = $("ha-entity-label"); const id = idInput.value.trim(); const label = labelInput.value.trim(); if (!id) { showMsg("Home Assistant entity ID is required."); return; } const existing = haEntities.find((entity) => entity.id === id); if (existing) existing.label = label; else haEntities.push({ id, label }); idInput.value = ""; labelInput.value = ""; showMsg(""); renderHA(); }
function renderConnections(connections) { const list = $("connections"); list.replaceChildren(); if (!connections.length) { const empty = document.createElement("li"); empty.className = "muted"; empty.textContent = "No remote APIs connected."; list.append(empty); return; } for (const c of connections) { const item = document.createElement("li"); item.className = "connection"; const text = document.createElement("div"); const name = document.createElement("strong"); name.textContent = c.name; text.append(name); const detail = document.createElement("small"); detail.textContent = c.base_url + (c.auth_configured ? " · auth configured" : ""); text.append(detail); const remove = document.createElement("button"); remove.type = "button"; remove.className = "remove"; remove.textContent = "Remove"; remove.addEventListener("click", () => act(async () => { await requestJSON("/connections/" + encodeURIComponent(c.id), { method: "DELETE" }); })); item.append(text, remove); list.append(item); } }
function renderConnectionsUnavailable(message) { const list = $("connections"); list.replaceChildren(); const item = document.createElement("li"); item.className = "msg"; item.textContent = "Unavailable · " + message; list.append(item); }
function renderDesktops(desktops, errors) { const root = $("desktops"); root.replaceChildren(); for (const error of errors) { const p = document.createElement("p"); p.className = "msg"; p.textContent = error.connection_name + ": " + error.error; root.append(p); } if (!desktops.length && !errors.length) { const p = document.createElement("p"); p.className = "muted"; p.textContent = "No desktops reported by connected APIs."; root.append(p); return; } for (const d of desktops) { const article = document.createElement("article"); article.className = "desktop"; const title = document.createElement("strong"); title.textContent = String(d.name || d.title || d.id || "Unnamed desktop"); const source = document.createElement("small"); source.textContent = String(d.box_identity || d.connection_name || "Unknown box") + " · " + String(d.connection_name || d.source_api || "API"); article.append(title, source); if (d.id && d.connection_id) { const watch = document.createElement("button"); watch.type = "button"; watch.textContent = "Watch"; watch.addEventListener("click", () => act(() => postJSON("/desktops/action", { connection_id: d.connection_id, desktop_id: d.id, action: "watch" }))); article.append(watch); } root.append(article); } }
function errorText(reason) { return reason instanceof Error ? reason.message : String(reason); }
function showMsg(text) { const el = $("msg"); el.hidden = !text; el.textContent = text; }
function busy(on) { busyState = on; ["btn-apply", "btn-revert", "btn-proxy-on", "btn-proxy-off", "btn-network-save", "btn-network-leave", "btn-ha-add", "btn-ha-save"].forEach((id) => { $(id).disabled = on; }); $("approvals-enabled").disabled = on || !policyAvailable; $("network-mode").disabled = on || !networkAvailable; $("network-login-server").disabled = on || !networkAvailable; $("network-auth-key").disabled = on || !networkAvailable; $("ha-entity-id").disabled = on || !haAvailable; $("ha-entity-label").disabled = on || !haAvailable; }
async function act(fn) { showMsg(""); busy(true); try { await fn(); await refresh(); } catch (e) { showMsg(errorText(e)); } finally { busy(false); } }
async function refresh() { const [status, policy, ha, connections, desktops] = await Promise.allSettled([getStatus(), getPolicy(), getHAAllowlist(), getConnections(), getDesktops()]); const errors = []; if (status.status === "fulfilled") renderStatus(status.value); else { const message = errorText(status.reason); renderStatusUnavailable(message); errors.push("status: " + message); } if (policy.status === "fulfilled") { renderPolicy(policy.value); renderNetwork(policy.value.network); } else { const message = errorText(policy.reason); renderPolicyUnavailable(message); renderNetworkUnavailable(message); errors.push("settings: " + message); } if (ha.status === "fulfilled") renderHAAllowlist(ha.value); else { const message = errorText(ha.reason); renderHAUnavailable(message); errors.push("HA allowlist: " + message); } if (connections.status === "fulfilled") renderConnections(connections.value.connections); else { const message = errorText(connections.reason); renderConnectionsUnavailable(message); errors.push("connections: " + message); } if (desktops.status === "fulfilled") renderDesktops(desktops.value.desktops, desktops.value.errors || []); else { const message = errorText(desktops.reason); renderDesktops([], [{ connection_name: "Desktops", error: message }]); errors.push("desktops: " + message); } showMsg(errors.join(" · ")); }
window.addEventListener("DOMContentLoaded", () => { $("btn-apply").addEventListener("click", () => act(() => postJSON("/apply", {}))); $("btn-revert").addEventListener("click", () => act(() => postJSON("/revert", {}))); $("btn-proxy-on").addEventListener("click", () => act(() => postJSON("/proxy", { enabled: true }))); $("btn-proxy-off").addEventListener("click", () => act(() => postJSON("/proxy", { enabled: false }))); $("btn-network-leave").addEventListener("click", () => act(() => postJSON("/policy", { network: { action: "leave" } }))); $("approvals-enabled").addEventListener("change", () => { const enabled = $("approvals-enabled"); act(() => postJSON("/policy", { enabled: enabled.checked })); }); $("network-mode").addEventListener("change", syncNetworkFields); $("network-form").addEventListener("submit", (event) => { event.preventDefault(); const mode = $("network-mode"); const loginServer = $("network-login-server"); const authKey = $("network-auth-key"); act(async () => { const body = { mode: mode.value, login_server: loginServer.value }; if (authKey.value.trim()) body.auth_key = authKey.value; await postJSON("/policy", { network: body }); authKey.value = ""; }); }); $("btn-ha-add").addEventListener("click", addHAEntityFromInputs); $("ha-form").addEventListener("submit", (event) => { event.preventDefault(); act(() => putJSON("/ha/allowlist", { entities: haEntities })); }); $("connection-form").addEventListener("submit", (event) => { event.preventDefault(); const name = $("connection-name"); const baseURL = $("connection-url"); const auth = $("connection-auth"); act(async () => { await postJSON("/connections", { name: name.value, base_url: baseURL.value, auth: auth.value }); name.value = ""; baseURL.value = ""; auth.value = ""; }); }); busy(false); refresh().catch((e) => showMsg(errorText(e))); });
